### ISSUE TITLE
Caching doesn't discriminate between evals with and without selector

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#436] opened 2020-12-05 02:21 UTC
**Description**
When I eval a pipeline: `coords --> interpolate --> source` or when I just eval the source `coords --> source` the cache will think it is the same. 

Thus, when I eval one of the two first, evaluating the second one gives me the wrong data. 

**Steps to Reproduce**
Sorry for the long example:
```python
point_interpolation = {
    "method": "nearest",
    "params": {
        "use_selector": False,  # By default, only the required data is retrieved remotely. This retrieves all the available data
        "remove_nan": True,     # Any nans will be removed prior to interpolation
        "time_scale": "1,M",    # When determining the closest neighbor, 1 month is considered equivalent to 1 degree
        "respect_bounds": False,# Extrapolation allowed
    },
}

soilscape = podpac.datalib.soilscape.SoilSCAPE20min(data_key="soil_moisture", site="Kendall_AZ", interpolation=point_interpolation)

time2 = podpac.crange('2015-12-01', '2016-02-01', '3,D', 'time')  # (start, stop, step)

# Make coordinates using the soilscape node - this selects soilscape probe coordinates 
time_series = soilscape.make_coordinates(depth=4.0, time=time2.coordinates)
time_series

cosmos_raw = podpac.datalib.cosmos_stations.COSMOSStationsRaw()
cosmos_daily = podpac.interpolators.Interpolate(source=cosmos_daily, interpolation=point_interpolation)
```
Here's the actual issue:
```python
o1 = cosmos_daily.eval(time_series)  # This passes a selector created form the interpolate node which subselects the source data
o2 = cosmos_raw.eval(time_series)  # This returns from the cache, but it shouldn't
```

**Expected Behavior**
The cache should take into account selectors passed through the eval.

**Observed Behavior**
The cache does not take into account selectors passed through the eval.

**Comment by jmilloy** [comment] 2020-12-06 19:23
The `DataCompositor` makes this difficult. The bug can be fixed in a DataSource by defining a custom `DataSource.eval` that does the selection and then calls super to get  to the `Node.eval` with the caching, but if you use a `DataCompositor` it still caches before even getting to its sources.

I fixed *this* example by not letting the `DataCompositor` cache (force `cache_output=False`) and having the COSMOSStationsRaw *sources* cache their output: 

```
    def sources(self):
        return np.array([COSMOSStation(station_data=item, cache_output=True) for item in self.stations_data["items"]])[self.has_data]
```

But a more general solution would be better. Do you think we can integrate the `_selector` into the cache key? Use the `method` attribute.

**Comment by mpu-creare** [comment] 2020-12-07 11:29
Does your above fix for `COSMOS` really work?

I'm not sure what the best solution is. Adding the `_selector` to the cache key seems like the right thing to do, but the `DataSource.eval` approach might fix more caching issues (order of operations, crs conflicts, etc). Worth thinking about carefully.

**Comment by jmilloy** [comment] 2021-05-18 20:27
I remembered about this when fixing #293, it's on my mind so I'll try to fix it soon.

**Comment by jmilloy** [comment] 2021-05-27 19:15
@mpu-creare I haven't been able to reproduce this. Can you check the example, or even better, provide an example that doesn't rely on external data?

The title of this issue suggests that we should be testing something like this with the same node and two different selectors:

```python3
o1 = node.eval(coords, selector_a)
o2 = node.eval(coords, selector_a)
assert o2 == o1
o3 = node.eval(coords, selector_b)
assert o3 != o1
```

Could you just help me out with a pair of selectors that will select different coordinates from the same coords when evaluated?

**Comment by mpu-creare** [comment] 2021-05-27 20:30
This is an issue for raw data sources:
```python
import podpac
coords = podpac.Coordinates([podpac.clinspace(0, 10, 11, 'alt')])
eval_coords = podpac.Coordinates([5], ['alt'])
selector = podpac.core.interpolation.selector.Selector(method='cubic')
node = podpac.core.data.array_source.ArrayRaw(source=np.arange(11), coordinates=coords)
node2 = podpac.interpolators.Interpolate(source=node, interpolation='cubic')
o1 = node._eval(eval_coords, None)  # This caches the raw data
o2 = node._eval(eval_coords, None, selector.select)  # This retrieves from the cache in some cases, whoops
o3 = node2.eval(eval_coords)  # This now doesn't have the correct data for interpolation
```

**Comment by jmilloy** [comment] 2021-05-28 14:08
Hmmm, I ran the above code with and without caching and got the same outputs.

**Comment by mpu-creare** [comment] 2021-05-28 14:32
Well.. the `ArrayRaw` datasource doesn't have caching (it's specifically disabled). I used to as an example.

**Comment by jmilloy** [comment] 2021-05-28 15:03
I enabled caching using `ArrayRaw(..., cache_ctrl=['ram'], cache_output=True)`.

Also, isn't the caching in `eval`, not `_eval`?

It's not pressing! But I need an example that produces the wrong output with caching on in order to fix this. I think guessing without an example is a bad idea. Plus, we need a test to accompany the fix, and it should fail now and pass with the fix.

**Closed** 2021-05-28 17:13 UTC
Labels: bug, confirmed

**Comment by jmilloy** [comment] 2021-05-28 17:23
I was suspecting the same thing, that it had since been fixed, or some part of it at least! Thanks.
